# Generated by Django 3.0 on 2020-01-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cnvmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bam_file', models.FileField(help_text='Enter bam File', upload_to='media/bam/')),
                ('bed_file', models.FileField(help_text='Enter bed File', upload_to='media/bed/')),
                ('fasta_file', models.FileField(help_text='Enter fasta File', upload_to='media/fasta/')),
                ('output_dir', models.CharField(max_length=200)),
            ],
        ),
    ]
