# Generated by Django 2.2.10 on 2020-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnvmodel',
            name='bam_file',
            field=models.FileField(help_text='Enter bam File/s', upload_to='bam/'),
        ),
        migrations.AlterField(
            model_name='cnvmodel',
            name='bed_file',
            field=models.FileField(help_text='Enter bed File', upload_to='bed/'),
        ),
        migrations.AlterField(
            model_name='cnvmodel',
            name='fasta_file',
            field=models.FileField(help_text='Enter fasta File', upload_to='fasta/'),
        ),
    ]
