# Generated by Django 3.0.6 on 2020-07-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0002_auto_20200206_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='cnv_app/bam_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Enter batch run name', max_length=200)),
                ('bam_files', models.ManyToManyField(to='cnv_app.BamFile')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='cnv_app/bed_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('document', models.FileField(upload_to='cnv_app/fasta')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='cnvmodel',
        ),
        migrations.AddField(
            model_name='batch',
            name='bed_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Bed'),
        ),
        migrations.AddField(
            model_name='batch',
            name='fasta_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Fasta'),
        ),
        migrations.AddField(
            model_name='batch',
            name='normal_files',
            field=models.ManyToManyField(related_name='normal_sample', to='cnv_app.BamFile'),
        ),
        migrations.AddField(
            model_name='batch',
            name='reference_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Reference'),
        ),
    ]
