# Generated by Django 3.0.6 on 2020-07-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0003_auto_20200713_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bed',
            new_name='BedFile',
        ),
        migrations.RenameModel(
            old_name='Fasta',
            new_name='FastaFile',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='reference_file',
        ),
        migrations.AlterField(
            model_name='batch',
            name='bam_files',
            field=models.ManyToManyField(related_name='bam_sample', to='cnv_app.BamFile'),
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
    ]
