# Generated by Django 3.0.6 on 2020-07-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnv_app', '0004_auto_20200713_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='Reference_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bamfile',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bamfile',
            name='document',
            field=models.FileField(upload_to='bam_files'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='batch',
            name='normal_files',
            field=models.ManyToManyField(blank=True, null=True, related_name='normal_sample', to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='bedfile',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bedfile',
            name='document',
            field=models.FileField(blank=True, upload_to='bed_files'),
        ),
        migrations.AlterField(
            model_name='fastafile',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fastafile',
            name='document',
            field=models.FileField(upload_to='fasta_files'),
        ),
        migrations.CreateModel(
            name='TargetCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='target_cov_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Scatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.ImageField(upload_to='scatter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.ImageField(upload_to='heatmap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.ImageField(upload_to='diagrams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='CopyNumberSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='copy_number_segment_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='CopyNumberRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='copy_number_ratio_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='AntiTargetCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='antiTarget_cov_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='reference_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Reference'),
        ),
    ]
