# Generated by Django 3.0.6 on 2020-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0005_auto_20200716_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antitargetcoverage',
            old_name='document',
            new_name='anti_target_coverage_document',
        ),
        migrations.RenameField(
            model_name='bamfile',
            old_name='document',
            new_name='bam_document',
        ),
        migrations.RenameField(
            model_name='bedfile',
            old_name='document',
            new_name='bed_document',
        ),
        migrations.RenameField(
            model_name='copynumberratio',
            old_name='document',
            new_name='copy_number_document',
        ),
        migrations.RenameField(
            model_name='copynumbersegment',
            old_name='document',
            new_name='copy_segment_document',
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='document',
            new_name='reference_document',
        ),
        migrations.RenameField(
            model_name='targetcoverage',
            old_name='document',
            new_name='target_coverage_document',
        ),
        migrations.RemoveField(
            model_name='fastafile',
            name='document',
        ),
        migrations.AddField(
            model_name='fastafile',
            name='fasta_document',
            field=models.FileField(blank=True, upload_to='fasta_files'),
        ),
        migrations.AlterField(
            model_name='bedfile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fastafile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
