# Generated by Django 3.0.6 on 2020-07-31 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnv_app', '0011_auto_20200731_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='log_file',
            field=models.FileField(null=True, upload_to='batch_log_files'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
