# Generated by Django 3.0.6 on 2020-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0013_auto_20200731_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageBinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='savvyCNV/coverageBinner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
