# Generated by Django 3.0.6 on 2020-08-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0015_coveragebinner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bamfile',
            name='seq_protocol',
            field=models.CharField(choices=[('H', 'Hybridization Capture'), ('A', 'Targeted Amplicon Sequencing'), ('W', 'Whole Genome Sequencing')], max_length=1, null=True),
        ),
    ]
