# Generated by Django 3.0.6 on 2020-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0017_auto_20200805_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antitargetbed',
            name='anti_target_bed_document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='antitargetcoverage',
            name='anti_target_coverage_document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bamfile',
            name='bam_document',
            field=models.FileField(upload_to='Data/bam_files'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='log_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bedfile',
            name='bed_document',
            field=models.FileField(blank=True, upload_to='Data/bed_files'),
        ),
        migrations.AlterField(
            model_name='copynumberratio',
            name='copy_number_document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='copynumbersegment',
            name='copy_segment_document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='fastafile',
            name='fasta_document',
            field=models.FileField(blank=True, upload_to='Data/fasta_files'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_document',
            field=models.FileField(upload_to='CNVKit/Reference_files'),
        ),
        migrations.AlterField(
            model_name='targetbed',
            name='target_bed_document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='targetcoverage',
            name='target_coverage_document',
            field=models.FileField(upload_to=''),
        ),
    ]
