# Generated by Django 3.0.6 on 2020-08-07 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnv_app', '0019_auto_20200805_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamfile',
            name='seq_protocol',
            field=models.CharField(choices=[('H', 'Hybridization Capture'), ('A', 'Targeted Amplicon Sequencing'), ('W', 'Whole Genome Sequencing')], default='H', max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=200)),
                ('analysis_type', models.CharField(choices=[('batch', 'batch'), ('pipeline', 'pipeline')], max_length=10, null=True)),
                ('log_file', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bam_files', models.ManyToManyField(related_name='bam_sample', to='cnv_app.BamFile')),
                ('bed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.BedFile')),
                ('fasta_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnv_app.FastaFile')),
                ('normal_files', models.ManyToManyField(blank=True, null=True, related_name='normal_sample', to='cnv_app.BamFile')),
                ('reference_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Reference')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='antitargetbed',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='antitargetcoverage',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='copynumberratio',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='copynumbersegment',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='scatter',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='targetbed',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.AlterField(
            model_name='targetcoverage',
            name='batch_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.Analysis'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
