# Generated by Django 3.0.6 on 2020-08-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0020_auto_20200807_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='bed_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.BedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='fasta_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.FastaFile'),
        ),
    ]
