# Generated by Django 3.0.6 on 2020-08-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0021_auto_20200807_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antitargetbed',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='antitargetcoverage',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='copynumberratio',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='copynumbersegment',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='diagram',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='heatmap',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='scatter',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='targetbed',
            old_name='batch_run',
            new_name='analysis_run',
        ),
        migrations.RenameField(
            model_name='targetcoverage',
            old_name='batch_run',
            new_name='analysis_run',
        ),
    ]
