# Generated by Django 3.0.6 on 2020-08-08 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnv_app', '0023_auto_20200807_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatmap',
            name='chr_range_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scatter',
            name='chr_range_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='normal_files',
            field=models.ManyToManyField(blank=True, related_name='normal_sample', to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='bam_files',
            field=models.ManyToManyField(blank=True, to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='bam_files',
            field=models.ManyToManyField(to='cnv_app.BamFile'),
        ),
    ]
