# Generated by Django 3.0.6 on 2020-08-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0025_auto_20200809_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='chr_sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
