# Generated by Django 3.0.6 on 2020-08-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0026_reference_chr_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_document',
            field=models.FileField(upload_to=''),
        ),
    ]
