# Generated by Django 3.0.6 on 2020-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0027_auto_20200811_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
