# Generated by Django 3.0.6 on 2020-08-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0028_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='segment_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sequence_method',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
