# Generated by Django 3.0.6 on 2020-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0029_auto_20200828_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
