# Generated by Django 3.0.6 on 2020-09-04 15:10

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0032_auto_20200904_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_document',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='CNVKit/Reference_files')),
        ),
    ]
