# Generated by Django 3.0.6 on 2020-09-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cnv_app', '0034_auto_20200905_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavvyAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=200)),
                ('log_file', models.FileField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bam_files_savvy', models.ManyToManyField(related_name='bam_savvy_sample', to='cnv_app.BamFile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coveragebinner',
            name='user',
        ),
        migrations.AddField(
            model_name='coveragebinner',
            name='bam_file_savvy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.BamFile'),
        ),
        migrations.CreateModel(
            name='SavvyCNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='savvyCNV/coverageBinner')),
                ('d_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.SavvyAnalysis')),
                ('coverage_files', models.ManyToManyField(to='cnv_app.CoverageBinner')),
            ],
        ),
        migrations.AddField(
            model_name='coveragebinner',
            name='analysis_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.SavvyAnalysis'),
        ),
    ]
