# Generated by Django 3.0.6 on 2020-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0035_auto_20200905_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragebinner',
            name='document',
            field=models.FileField(upload_to='savvyCNV/'),
        ),
        migrations.AlterField(
            model_name='savvycnv',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
