# Generated by Django 3.0.6 on 2020-09-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0036_auto_20200905_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavvySelectCNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='')),
                ('d_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cnv_app.SavvyAnalysis')),
                ('coverage_files', models.ManyToManyField(to='cnv_app.CoverageBinner')),
            ],
        ),
    ]
