# Generated by Django 3.0.6 on 2020-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0039_dataset_uploadfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadfile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
