# Generated by Django 3.0.6 on 2020-09-16 07:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0041_auto_20200915_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='log_file',
            field=models.FileField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='antitargetbed',
            name='anti_target_bed_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='antitargetcoverage',
            name='anti_target_coverage_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bamfile',
            name='bam_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bedfile',
            name='bed_document',
            field=models.FileField(blank=True, max_length=500, upload_to='Data/bed_files'),
        ),
        migrations.AlterField(
            model_name='copynumberratio',
            name='copy_number_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='copynumbersegment',
            name='copy_segment_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='coveragebinner',
            name='document',
            field=models.FileField(max_length=500, upload_to='savvyCNV/'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='document',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='fastafile',
            name='fasta_document',
            field=models.FileField(blank=True, max_length=500, upload_to='Data/fasta_files'),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='document',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_document',
            field=models.FileField(max_length=500, upload_to=django.core.files.storage.FileSystemStorage(location='CNVKit/Reference_files')),
        ),
        migrations.AlterField(
            model_name='savvyanalysis',
            name='log_file',
            field=models.FileField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='savvycnv',
            name='document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='savvyselectcnv',
            name='document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='scatter',
            name='document',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='targetbed',
            name='target_bed_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='targetcoverage',
            name='target_coverage_document',
            field=models.FileField(max_length=500, upload_to=''),
        ),
    ]
