# Generated by Django 3.0.6 on 2020-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0042_auto_20200916_0909'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='copynumbersegment',
        #     name='purity',
        #     field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        # ),
    ]
