# Generated by Django 3.0.6 on 2020-09-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0043_copynumbersegment_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='reference_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.Reference'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='bam_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='scatter',
            name='bam_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cnv_app.BamFile'),
        ),
    ]
