# Generated by Django 3.0.6 on 2020-09-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0044_auto_20200917_1942'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='copynumbersegment',
        #     name='purity',
        # ),
        migrations.AlterField(
            model_name='analysis',
            name='bed_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.BedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='fasta_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.FastaFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='reference_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.Reference'),
        ),
        migrations.AlterField(
            model_name='coveragebinner',
            name='bam_file_savvy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='diagram',
            name='bam_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.BamFile'),
        ),
        migrations.AlterField(
            model_name='scatter',
            name='bam_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnv_app.BamFile'),
        ),
    ]
