# Generated by Django 3.0.6 on 2020-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnv_app', '0045_auto_20200919_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savvyanalysis',
            name='bam_files_savvy',
        ),
        migrations.RemoveField(
            model_name='savvyanalysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savvycnv',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='savvycnv',
            name='coverage_files',
        ),
        migrations.RemoveField(
            model_name='savvyselectcnv',
            name='analysis_run',
        ),
        migrations.RemoveField(
            model_name='savvyselectcnv',
            name='coverage_files',
        ),
        migrations.DeleteModel(
            name='CoverageBinner',
        ),
        migrations.DeleteModel(
            name='SavvyAnalysis',
        ),
        migrations.DeleteModel(
            name='SavvyCNV',
        ),
        migrations.DeleteModel(
            name='SavvySelectCNV',
        ),
    ]
