version: '3'

services:
  django:
    build: .
    volumes:
      - ./cnv_proj:/cnv_proj
      - ./scripts:/scripts
    environment:
      - SECRET_KEY=HTNlQCxK8vNN8d79dfPtTjCsxpGLPCMFlCMw5DFWtZ6WwW5RVpsc
      - ALLOWED_HOST=127.0.0.1,localhost,nginx,141.39.185.138,172.18.0.3
      - DEBUG=1
      - INIT_DB=0
    depends_on:
      - postgres
  nginx:
    image: nginx
    volumes:
      - ./cnv_proj/cnv_app/static:/vol/static
      - ./cnv_proj/media:/vol/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    ports:
      - "80:80"
    depends_on:
      - django
  postgres:
    image: library/postgres:12.4
    # build: ./postgres
    environment:
      - POSTGRES_USER=em
      - POSTGRES_PASSWORD=mako'zz
      - POSTGRES_DB=cnv_app
#volumes:
#  static_data: